name: Pipeline

run-name: Run triggered by ${{ github.actor }}

on: [push, workflow_dispatch]

env: 
  DOTNET_INSTALL_DIR: /home/actions-runner/dotnet

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # fetches all history for all branches and tags
      - name: Set up .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9
      - name: Build
        run: |
          dotnet build Deo.Backend
          dotnet build Deo.Frontend
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: build
          path: |
            **/bin/
            **/obj/

  test:
    runs-on: self-hosted
    needs: build
    steps:

      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # fetches all history for all branches and tags

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build

# The cache is configured to cache dependencies for the test projects.
      - name: Set up .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9
          cache: true
          cache-dependency-path: |
            Deo.Backend.Tests/packages.lock.json
            Deo.Frontend.Tests/packages.lock.json
      
# The restore step uses --locked-mode to ensure that the exact versions specified in the lock files are used.
      - name: Restore dependencies
        run: |
          dotnet restore --locked-mode Deo.Backend.Tests
          dotnet restore --locked-mode Deo.Frontend.Tests
      
# The test step runs the tests without restoring dependencies again, as they have already been restored in the previous step.
      - name: Test projects
        run: |
          dotnet test --no-restore Deo.Backend.Tests
          dotnet test --no-restore Deo.Frontend.Tests

# Finally, the test artifacts (such as test results) are uploaded for further analysis or reporting.
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: test
          path: |
            **/bin/
            **/obj/
